name: Tests

# Workflow for iOS tests
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: List project structure
      working-directory: TarotApp
      run: |
        pwd
        ls -la
        echo "Checking for workspace..."
        ls -la *.xcworkspace
        
    - name: List available schemes
      working-directory: TarotApp
      run: |
        xcodebuild -list -workspace Lunalit.xcworkspace
        
    - name: List available simulators
      run: |
        xcrun simctl list devices --json | jq '.devices."iOS 18.5" | .[] | select(.isAvailable == true) | .name'
        
    - name: Build App
      working-directory: TarotApp
      run: |
        xcodebuild build \
          -workspace Lunalit.xcworkspace \
          -scheme Lunalit \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
    - name: Run Tests
      working-directory: TarotApp
      run: |
        xcodebuild test \
          -workspace Lunalit.xcworkspace \
          -scheme Lunalit \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -enableCodeCoverage YES \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO