name: Tests

# Workflow for iOS tests
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Tuist with Mise
      uses: jdx/mise-action@v2
      
    - name: Generate Xcode project
      working-directory: TarotApp
      run: |
        tuist generate
        
    - name: List project structure (for debugging)
      working-directory: TarotApp
      run: |
        pwd
        ls -la
        echo "Checking for generated workspace..."
        ls -la *.xcworkspace
        
    - name: List available schemes
      working-directory: TarotApp
      run: |
        xcodebuild -list -workspace Lunalit.xcworkspace
        
    - name: List available simulators
      run: |
        xcrun simctl list devices --json | jq '.devices | to_entries[] | select(.key | startswith("iOS")) | .key'
        xcrun simctl list devices available
        
    - name: Build App
      working-directory: TarotApp
      run: |
        defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
        defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        tuist build Lunalit -- -IDESkipPackagePluginFingerprintValidation=YES -IDESkipMacroFingerprintValidation=YES
        
    - name: Run Tests
      working-directory: TarotApp
      run: |
        tuist test LunalitTests -- -IDESkipPackagePluginFingerprintValidation=YES -IDESkipMacroFingerprintValidation=YES