name: Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Build and Test
    runs-on: macos-14  # Explicitly use macos-14
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: 1
      IDESkipPackagePluginValidation: YES
      IDESkipMacroValidation: YES
      # Configuration Management - Environment Variables for CI
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-test-key-for-ci-builds-only' }}
      API_BASE_URL: https://api.openai.com/v1/
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: jdx/mise-action@v2
    
    # Explicitly select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
      
    - name: Build Application
      working-directory: TarotApp
      run: |
        tuist build -- -skipPackagePluginValidation -skipMacroValidation
        
    - name: Run Tests
      working-directory: TarotApp
      run: |
        tuist test -- -skipPackagePluginValidation -skipMacroValidation 