name: Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # This is important when using PAT
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      
    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
      
    - name: Generate Xcode Project
      run: |
        tuist generate
        
    - name: Build and Test
      run: |
        # Run tests with detailed output
        xcodebuild test \
          -scheme TarotApp \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -enableCodeCoverage YES \
          | xcpretty -c && exit ${PIPESTATUS[0]} 