name: Tests

# Workflow for iOS tests
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: 1
      # Plugin handling environment variables
      IDESkipPackagePluginFingerprintValidation: YES
      IDESkipMacroFingerprintValidation: YES
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: jdx/mise-action@v2
      
    - name: Build Application
      working-directory: TarotApp
      run: tuist build
        
    - name: Run Tests
      working-directory: TarotApp
      run: tuist test