name: Tests

# Workflow for iOS tests
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      
    - name: Install mise
      uses: jdx/mise-action@v2
    
    - name: Generate Xcode Project
      run: tuist generate
        
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme Lunalit \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -enableCodeCoverage YES \
          | xcpretty -c && exit ${PIPESTATUS[0]} 